# netlify.toml

[build]
  # La directory delle funzioni rimane la stessa
  functions = "netlify/functions"

# Questa sezione è la nostra unica e ultima speranza
[functions]
  # Dice a Netlify di usare il bundler esbuild
  node_bundler = "esbuild"
  # Questa è la riga MAGICA.
  # Dice a esbuild: "Il pacchetto '@netlify/blobs' è esterno. Non toccarlo."
  external_node_modules = ["@netlify/blobs"]